name: Vuejs github pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Use Nodejs 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Dist folder
        uses: actions/upload-artifact@v3
        with:
          path: dist
