name: Vuejs github pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Nodejs 16 vue deploy
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          publish_dir: ./dist
      - run: npm i
      - run: npm run build
